title: Adfinis Helm Charts
locale                  : "en-US"
remote_theme: gianklug/jekyll-theme-adfinis-ng
email                   : support@adfinis.com
description             : >-
  Welcome to Adfinis!
url:                    : "https://pages.adfinis.com"



header:
  button:
    title: "Contact"
    href: "https://adfinis.com/kontakt/"

footer:
  blog:
    name: "Blog"
    href: "https://adfinis.com/blog/"
  privacy:
    name: "Privacy policy"
    href: "https://adfinis.com/datenschutzerklaerung/"
  linkedin:
    href: "https://www.linkedin.com/company/adfinis-com"
  github:
    href: "https://github.com/adfinis/helm-charts"
  twitter:
    href: "https://twitter.com/adfinis"
